[package]
name = "searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
colored = "2.1.0"
fuzzy-matcher = "0.3.7"
inquire = "0.7.5"
rayon = "1.10.0"
strum = "0.26.2"
strum_macros = "0.26.2"
